### ISSUE TITLE
Add notes and slides from the different ICAT schema discussion meetings

### ISSUE THREAD

**Issue by agbeltran** [icatproject/icatproject.github.io#39]
Add the slides and notes from the discussions around the ICAT schema changes, linking to the relevant issues in the icat.server component.

**Comment by agbeltran** [comment]
cc @stuartpullinger @RKrahl - it would be great to upload the slides from the discussions to the website
+

**Comment by RKrahl** [comment]
Sure! Where shall I put the slides?

**Comment by agbeltran** [comment]
I suggest creating a specific folder under: https://github.com/icatproject/icatproject.github.io/tree/gatsbyjs/content/collaboration/communication
and having sub-folders for each of the meetings.

We need to include the slides + move all the content from the google docs to the website
