### ISSUE TITLE
Change link to latest ICAT schema documentation

### ISSUE THREAD

**Issue by agbeltran** [icatproject/icatproject.github.io#7]
The page https://icatproject.github.io/user-documentation/icat-schema/ (source: https://github.com/icatproject/icatproject.github.io/blob/gatsbyjs/content/user-documentation/icat-schema.md) is pointing to ICAT schema 4.8 and the latest is https://repo.icatproject.org/site/icat/server/4.10.0/schema.html

**Comment by VKTB** [comment]
@agbeltran The [Useful Links](https://icatproject.github.io/about/useful-links/) page is also pointing to ICAT schema 4.8.0 so I will update that as well. I notice that the three links above the Schema link also point to 4.8.0, so was wondering whether they need to be updated too?

**Comment by VKTB** [comment]
Realise that Alejandra is quite busy so maybe you guys can provide an answer to the question in my last post? @stuartpullinger @louise-davies

**Comment by stuartpullinger** [comment]
Yes - please update the other links too. The link to the REST API will have to point to the 4.9.1 api as, in the later versions, the link is broken. (The API hasn't changed but the software we used to generate the api docs needs a licence update).
