### ISSUE TITLE
Remove link to waffle.io

### ISSUE THREAD

**Issue by agbeltran** [icatproject/icatproject.github.io#8]
We are not using waffle.io anylonger, so the link to https://waffle.io/icatproject/icat.server needs to be removed from the Links on the left hand-side menu.

**Comment by 96RadhikaJadhav** [comment]
@agbeltran  Could you please assign this issue to me and also guide me to the filename where this link can be removed?

**Comment by VKTB** [comment]
@agbeltran While working on this issue yesterday, I did a quick search and noticed that the [Components of the ICAT Project](https://icatproject.github.io/about/components-of-the-icat-project/) and a few monthly meeting pages contain a link to the waffle.io site. Should I remove these too?

**Comment by VKTB** [comment]
Realise that Alejandra is quite busy so maybe you guys can provide an answer to the question in my last post? @stuartpullinger @louise-davies

**Comment by stuartpullinger** [comment]
Yes - please remove all links to waffe.io. Thanks!
